version: "3.9"
services:
  web:
    container_name: nginx_web
    build:
      context: ./              # dockerfile 위치
      dockerfile: Dockerfile   # 개인 docker file
    volumes:
      - ./:/app
    ports:
      - 80:80
