version: "3.9"
services:
  reverse_proxy:
    container_name: nginx_reverse_proxy
    build: 
      context: ./reverse_proxy
      dockerfile: Dockerfile.proxy
    ports:
      - 80:80
      - 443:443
    # env_file:
    #   - .env


  web:
    container_name: nginx_web
    build:
      context: ./web                # dockerfile 위치
      dockerfile: Dockerfile.web    # 개인 docker file
    volumes:
      - ./web:/app/web
    ports:
      - 8080:80
