version: "3.9"
services:
  reverse_proxy:
    container_name: nginx-reverse-proxy
    build: 
      context: ./reverse_proxy
      dockerfile: Dockerfile.proxy
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
    - 80:80
    - 443:443

  web:
    container_name: nginx-web
    build:
      context: ./web                # dockerfile 위치
      dockerfile: Dockerfile.web    # 개인 docker file
    volumes:
      - ./web:/app/web
    ports:
      - 8080:8080

  certbot:
    container_name: nginx-certbot
    image: certbot/certbot
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot